### ISSUE TITLE
faulty alignment of PIDs in tree view, column width

### ISSUE THREAD

**Issue by pmattern** [lxqt/qps#9]
By default the alignment of PIDs in tree view is frequently faulty in levels ≥ 3 like in this screenshot

![qps_pid-alignment](https://cloud.githubusercontent.com/assets/9860801/9179835/4abcf9fc-3f9f-11e5-8ed5-c2dc9a56bedb.png)

The problem doesn't seem to exist right after launching qps but affects the majority of the said PIDs once the view was updated automatically several times.

Maybe it's due to column `PID` not being wide enough and could be fixed by making the columns' width adjustable.
This could probably best be achieved by making the spacer between the headers draggable, e. g. between `PID` and `TTY`, `TTY` and `USER` and so on when `Basic Fields` is chosen from menu `Field`. A feature like is desirable independent from this issue anyway.

But attempts to avoid an alignment as shown in the screenshot should be made whether or not it's related to the columns' width.

**Comment by doktor5000** [comment]
Saw this too, although I thought it was because I selected a monospace font instead of the default.
And yes, draggable spacers in the header would be really nice, and should also make it possible to apply an optimal width to the columns automatically.

**Comment by RalfJung** [comment]
To me this actually looks like a sign error somewhere in the computation of the position of the PID text -- the PIDs have exactly the opposite structure of the tree, i.e., deeply nested PIDs are printed on the left, top-level PIDs are printed o the right.

In any case, this looks both broken and confusing.

**Comment by tsujan** [comment]
The real causes of this issue:

(1) Inappropriate custom widgets are used instead of subclassing available Qt widgets;
(2) The window style is forced.

Actually, Fusion doesn't show any tree lines and tree lines shouldn't be forced at all. They should be drawn in a standard way, so that they're shown by those widget styles that have them.

This is a screenshot that shows several fixes, including tree lines:

![tree](https://user-images.githubusercontent.com/981076/28462074-d82a24ee-6e2e-11e7-88d9-f1d0272c7d76.png)

The screenshot is taken with Kvantum but Breeze shows the same lines (Fusion shows only the indicators).

As you see, some lines cannot be drawn and there is still a bad alignment (in parts of the window outside the screenshot) but, IMO, this is the most that can be done for now. Later, we should change the structure of the code.

**Comment by tsujan** [comment]
Superseded by https://github.com/lxqt/qps/issues/172

Have fixed it but waiting for my previous PR to be merged.
